spring:
  application:
    name: encoding-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.netflix.encodingservice.event.VideoUploadedEvent

    producer:
      key-serializer:   org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

#AWS Configuration
aws:
  access-key : ${AWS_ACCESS_KEY:AKIA55ICQMWCAIJB37M3}
  secret-key : ${AWS_SECRET_KEY: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}
  region : ${AWS_REGION:ap-south-1}  #Check it once from AWS Account
  s3:
    bucket-name: ${AWS_BUCKET_NAME:netflix-streaming-videos-956172363140-ap-south-1-an}

#FFmpeg Configuration
ffmpeg:
  path: ${FFMPEG_PATH:C:/Users/M S I/Downloads/ffmpeg-8.1.2-essentials_build/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe}

#Temp directory for encoding
encoding:
  base-path: ${TEMP_DIR:C:/Users/M S I/Downloads/tmp/encoding}

management:
  endpoints:
    web:
      exposure:
        include: health,info
